language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kgurbey/react-test -f ./client/Docker.dev ./client

scripts:
  - docker run -e CI=true kgurbey/react-test npm test

after_success:
  - docker build -t kgurbey/multi-client ./client
  - docker build -t kgurbey/multi-nginx ./nginx
  - docker build -t kgurbey/multi-server ./server
  - docker build -t kgurbey/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kgurbey/multi-client 
  - docker push kgurbey/multi-nginx
  - docker push kgurbey/multi-server
  - docker push kgurbey/multi-worker
